import type { QuranAyah, SurahMeta } from "@/lib/content/types";

type RawSurah = QuranAyah[];

export const quranSurahs: Record<number, RawSurah> = {
  1: require("./raw/quran/surahs/001.json"),
  2: require("./raw/quran/surahs/002.json"),
  3: require("./raw/quran/surahs/003.json"),
  4: require("./raw/quran/surahs/004.json"),
  5: require("./raw/quran/surahs/005.json"),
  6: require("./raw/quran/surahs/006.json"),
  7: require("./raw/quran/surahs/007.json"),
  8: require("./raw/quran/surahs/008.json"),
  9: require("./raw/quran/surahs/009.json"),
  10: require("./raw/quran/surahs/010.json"),
  11: require("./raw/quran/surahs/011.json"),
  12: require("./raw/quran/surahs/012.json"),
  13: require("./raw/quran/surahs/013.json"),
  14: require("./raw/quran/surahs/014.json"),
  15: require("./raw/quran/surahs/015.json"),
  16: require("./raw/quran/surahs/016.json"),
  17: require("./raw/quran/surahs/017.json"),
  18: require("./raw/quran/surahs/018.json"),
  19: require("./raw/quran/surahs/019.json"),
  20: require("./raw/quran/surahs/020.json"),
  21: require("./raw/quran/surahs/021.json"),
  22: require("./raw/quran/surahs/022.json"),
  23: require("./raw/quran/surahs/023.json"),
  24: require("./raw/quran/surahs/024.json"),
  25: require("./raw/quran/surahs/025.json"),
  26: require("./raw/quran/surahs/026.json"),
  27: require("./raw/quran/surahs/027.json"),
  28: require("./raw/quran/surahs/028.json"),
  29: require("./raw/quran/surahs/029.json"),
  30: require("./raw/quran/surahs/030.json"),
  31: require("./raw/quran/surahs/031.json"),
  32: require("./raw/quran/surahs/032.json"),
  33: require("./raw/quran/surahs/033.json"),
  34: require("./raw/quran/surahs/034.json"),
  35: require("./raw/quran/surahs/035.json"),
  36: require("./raw/quran/surahs/036.json"),
  37: require("./raw/quran/surahs/037.json"),
  38: require("./raw/quran/surahs/038.json"),
  39: require("./raw/quran/surahs/039.json"),
  40: require("./raw/quran/surahs/040.json"),
  41: require("./raw/quran/surahs/041.json"),
  42: require("./raw/quran/surahs/042.json"),
  43: require("./raw/quran/surahs/043.json"),
  44: require("./raw/quran/surahs/044.json"),
  45: require("./raw/quran/surahs/045.json"),
  46: require("./raw/quran/surahs/046.json"),
  47: require("./raw/quran/surahs/047.json"),
  48: require("./raw/quran/surahs/048.json"),
  49: require("./raw/quran/surahs/049.json"),
  50: require("./raw/quran/surahs/050.json"),
  51: require("./raw/quran/surahs/051.json"),
  52: require("./raw/quran/surahs/052.json"),
  53: require("./raw/quran/surahs/053.json"),
  54: require("./raw/quran/surahs/054.json"),
  55: require("./raw/quran/surahs/055.json"),
  56: require("./raw/quran/surahs/056.json"),
  57: require("./raw/quran/surahs/057.json"),
  58: require("./raw/quran/surahs/058.json"),
  59: require("./raw/quran/surahs/059.json"),
  60: require("./raw/quran/surahs/060.json"),
  61: require("./raw/quran/surahs/061.json"),
  62: require("./raw/quran/surahs/062.json"),
  63: require("./raw/quran/surahs/063.json"),
  64: require("./raw/quran/surahs/064.json"),
  65: require("./raw/quran/surahs/065.json"),
  66: require("./raw/quran/surahs/066.json"),
  67: require("./raw/quran/surahs/067.json"),
  68: require("./raw/quran/surahs/068.json"),
  69: require("./raw/quran/surahs/069.json"),
  70: require("./raw/quran/surahs/070.json"),
  71: require("./raw/quran/surahs/071.json"),
  72: require("./raw/quran/surahs/072.json"),
  73: require("./raw/quran/surahs/073.json"),
  74: require("./raw/quran/surahs/074.json"),
  75: require("./raw/quran/surahs/075.json"),
  76: require("./raw/quran/surahs/076.json"),
  77: require("./raw/quran/surahs/077.json"),
  78: require("./raw/quran/surahs/078.json"),
  79: require("./raw/quran/surahs/079.json"),
  80: require("./raw/quran/surahs/080.json"),
  81: require("./raw/quran/surahs/081.json"),
  82: require("./raw/quran/surahs/082.json"),
  83: require("./raw/quran/surahs/083.json"),
  84: require("./raw/quran/surahs/084.json"),
  85: require("./raw/quran/surahs/085.json"),
  86: require("./raw/quran/surahs/086.json"),
  87: require("./raw/quran/surahs/087.json"),
  88: require("./raw/quran/surahs/088.json"),
  89: require("./raw/quran/surahs/089.json"),
  90: require("./raw/quran/surahs/090.json"),
  91: require("./raw/quran/surahs/091.json"),
  92: require("./raw/quran/surahs/092.json"),
  93: require("./raw/quran/surahs/093.json"),
  94: require("./raw/quran/surahs/094.json"),
  95: require("./raw/quran/surahs/095.json"),
  96: require("./raw/quran/surahs/096.json"),
  97: require("./raw/quran/surahs/097.json"),
  98: require("./raw/quran/surahs/098.json"),
  99: require("./raw/quran/surahs/099.json"),
  100: require("./raw/quran/surahs/100.json"),
  101: require("./raw/quran/surahs/101.json"),
  102: require("./raw/quran/surahs/102.json"),
  103: require("./raw/quran/surahs/103.json"),
  104: require("./raw/quran/surahs/104.json"),
  105: require("./raw/quran/surahs/105.json"),
  106: require("./raw/quran/surahs/106.json"),
  107: require("./raw/quran/surahs/107.json"),
  108: require("./raw/quran/surahs/108.json"),
  109: require("./raw/quran/surahs/109.json"),
  110: require("./raw/quran/surahs/110.json"),
  111: require("./raw/quran/surahs/111.json"),
  112: require("./raw/quran/surahs/112.json"),
  113: require("./raw/quran/surahs/113.json"),
  114: require("./raw/quran/surahs/114.json"),
};

const SURAH_NAMES = [
  "الفاتحة", "البقرة", "آل عمران", "النساء", "المائدة", "الأنعام", "الأعراف", "الأنفال", "التوبة", "يونس", "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه", "الأنبياء", "الحج", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم", "لقمان", "السجدة", "الأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر", "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الأحقاف", "محمد", "الفتح", "الحجرات", "ق", "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة", "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحاقة", "المعارج", "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس", "التكوير", "الانفطار", "المطففين", "الانشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد", "الشمس", "الليل", "الضحى", "الشرح", "التين", "العلق", "القدر", "البينة", "الزلزلة", "العاديات", "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر", "المسد", "الإخلاص", "الفلق", "الناس",
];

export const surahCatalog: SurahMeta[] = SURAH_NAMES.map((name, index) => ({
  number: index + 1,
  name,
  ayahCount: quranSurahs[index + 1]?.length ?? 0,
}));

export function getSurah(number: number): QuranAyah[] {
  return quranSurahs[number] ?? [];
}
