import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppScreen, Metric, ScreenTitle, Surface } from "@/components/dalil-ui";
import { getDailyAyah, getDailyMessage } from "@/lib/content/daily";
import { useAppState } from "@/lib/state/app-state";
import { palette } from "@/lib/ui/theme";

const actions = [
  { href: "/(tabs)/azkar", icon: "wb-sunny" as const, title: "الأذكار", subtitle: "ورد الصباح والمساء" },
  { href: "/(tabs)/quran", icon: "menu-book" as const, title: "القرآن", subtitle: "قراءة واستئناف" },
  { href: "/(tabs)/duas", icon: "auto-stories" as const, title: "الأدعية", subtitle: "مختارات جامعة" },
  { href: "/masbaha", icon: "touch-app" as const, title: "المسبحة", subtitle: "عداد يومي" },
  { href: "/tasks", icon: "check-circle-outline" as const, title: "المهام", subtitle: "وردك اليومي" },
  { href: "/names", icon: "spa" as const, title: "أسماء الله", subtitle: "معانٍ وتدبر" },
];

export default function HomeScreen() {
  const { state, hydrated } = useAppState();
  const ayah = getDailyAyah();
  const completedTasks = state.tasks.filter((task) => task.completed).length;
  return <AppScreen><FlatList columnWrapperStyle={styles.gridRow} contentContainerStyle={styles.content} data={actions} keyExtractor={(item) => item.title} numColumns={2} ListHeaderComponent={<View style={styles.header}><View style={styles.topLine}><View><Text style={styles.greeting}>السلام عليك</Text><Text style={styles.subGreeting}>{hydrated ? "كل ما تحتاجه محفوظ على جهازك" : "جارٍ استعادة تقدمك المحلي…"}</Text></View><View style={styles.brandMark}><MaterialIcons color="#FFFFFF" name="auto-awesome" size={20} /></View></View><Surface style={styles.ayahCard}><Text style={styles.ayahLabel}>آية اليوم</Text><Text style={styles.ayahText}>{ayah?.text ?? "اذكر الله يطمئن قلبك"}</Text><Text style={styles.ayahMeta}>{ayah ? `${ayah.surah} · آية ${ayah.verseNumber}` : ""}</Text></Surface><View style={styles.metrics}><Metric label="التزام" value={`${Math.round((completedTasks / Math.max(state.tasks.length, 1)) * 100)}%`} /><Metric accent="gold" label="تسبيح" value={String(state.daily.tasbeehCount)} /><Metric label="مهام" value={`${completedTasks}/${state.tasks.length}`} /></View><Surface style={styles.message}><Text style={styles.messageLabel}>رسالة اليوم</Text><Text style={styles.messageText}>{getDailyMessage()}</Text></Surface>{state.quranBookmark ? <Pressable onPress={() => router.push(`/quran/${state.quranBookmark?.surah}` as never)}><Surface style={styles.resume}><MaterialIcons color={palette.gold} name="bookmark" size={22} /><View style={styles.resumeCopy}><Text style={styles.resumeTitle}>تابع قراءتك</Text><Text style={styles.resumeText}>السورة {state.quranBookmark.surah} · الآية {state.quranBookmark.ayah}</Text></View></Surface></Pressable> : null}<ScreenTitle eyebrow="استخدام دون إنترنت" title="استكشف الأقسام" /></View>} renderItem={({ item }) => <Pressable onPress={() => router.push(item.href as never)} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><View style={styles.actionIcon}><MaterialIcons color={palette.primary} name={item.icon} size={23} /></View><Text style={styles.actionTitle}>{item.title}</Text><Text style={styles.actionSubtitle}>{item.subtitle}</Text></Pressable>} /></AppScreen>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 28 }, header: { gap: 16, marginBottom: 4 }, topLine: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, greeting: { color: palette.ink, fontSize: 26, fontWeight: "900", textAlign: "right" }, subGreeting: { color: palette.muted, fontSize: 13, marginTop: 3, textAlign: "right" }, brandMark: { alignItems: "center", backgroundColor: palette.primary, borderRadius: 18, height: 48, justifyContent: "center", width: 48 }, ayahCard: { backgroundColor: "#F2F7F4", padding: 18 }, ayahLabel: { color: palette.gold, fontSize: 12, fontWeight: "900", textAlign: "right" }, ayahText: { color: palette.ink, fontSize: 19, fontWeight: "700", lineHeight: 35, marginTop: 8, textAlign: "right" }, ayahMeta: { color: palette.muted, fontSize: 12, marginTop: 10, textAlign: "right" }, metrics: { flexDirection: "row", gap: 8 }, message: { padding: 16 }, messageLabel: { color: palette.gold, fontSize: 12, fontWeight: "900", textAlign: "right" }, messageText: { color: palette.ink, fontSize: 15, lineHeight: 25, marginTop: 7, textAlign: "right" }, resume: { alignItems: "center", backgroundColor: palette.goldSoft, flexDirection: "row", padding: 14 }, resumeCopy: { alignItems: "flex-end", flex: 1, marginRight: 10 }, resumeTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, resumeText: { color: palette.muted, fontSize: 12, marginTop: 3 }, gridRow: { gap: 12 }, action: { alignItems: "flex-end", backgroundColor: palette.surface, borderColor: palette.border, borderRadius: 20, borderWidth: 1, flex: 1, marginBottom: 12, minHeight: 142, padding: 14 }, actionIcon: { alignItems: "center", alignSelf: "flex-end", backgroundColor: palette.primarySoft, borderRadius: 14, height: 42, justifyContent: "center", width: 42 }, actionTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", marginTop: 14, textAlign: "right" }, actionSubtitle: { color: palette.muted, fontSize: 11, marginTop: 4, textAlign: "right" }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] } });
